name: sahel_risk_app
description: A new Flutter project for Sahel multi-hazard risk assessment.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  csv: ^5.0.2
  flutter_map_geojson: ^1.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/hazard.csv
    - assets/data/vulnerability.csv
    - assets/data/exposure.csv
    - assets/data/lcc.csv
    - assets/geojson/SAHEL_Risk.geojson

